version: "3.8"
services:
  db:
    image: mysql:8.0
    expose:
      - "3306"
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=wordloop_2022_4
      - MYSQL_DATABASE=wordloop_data
    volumes:
      - ./src/db/migrations/V2022-13-04-18.56.sql:/docker-entrypoint-initdb.d/migration.sql
    command: --default-authentication-plugin=mysql_native_password
      
    networks:
      - wordloopAPI
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - wordloopAPI
networks:
  wordloopAPI:
