version: "3.8"
services:

  mysql_server:
    image: mysql:8.0
    expose:
      - "3307"
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=1010
      - MYSQL_DATABASE=wordloop_data
    volumes:
      - ./src/db/migrations/V2022-13-04-18.56.sql:/docker-entrypoint-initdb.d/migration.sql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mysql_server